### PR TITLE
Advanced git lesson

### PR DESCRIPTION
**Pull request by hallez**
I have a first draft of the lesson for the advanced git section completed for you to review. Plse ignore the fact that there are commits coming from multiple people - my partner and I share a home desktop and sometimes our github accounts get mixed up (and I was lazy about overwriting authorship for some of them).

### CODE REVIEW

**Review by pab2163 — CHANGES_REQUESTED** [review]
Thanks Halle, this looks awesome! If you could make just a few changes that would be great

-I think we really want to heavily emphasize the 'fetch/pull before you start working in a shared repo' aspect of collaboration to help avoid merge conflicts. Could you maybe make something along these lines as one of the main headers in the class topics? I think a lot of the material you have could be put under that header
-If you could a last section section at the end with a short overview/recap of the main points of the lesson (3-4 bullets is what we usually do), that would be great!

**Comment by hallez** [comment]
I've made those requested changes, Paul. Can you take another look?

**Comment by hallez** [comment]
Paul, I'm also ready for you to review the challenge on this branch. Let me know if you need any modifications once you review these!

**Comment by pab2163** [comment]
Will take a look soon, thanks so much!

**Review by pab2163 — CHANGES_REQUESTED** [review]
I think the lesson is looking great, thank you!

For the challenge, I think we'll want it to be a little bit more specific on the instructions for steps 2 and beyond on *which* repo to do this in. I think one good way to do this would be, prior to part 2, to have people create a new repo on Github and add a readme or something to get started, just so the challenge is self-contained from there to the end (and students won't be creating merge conflicts in their existing repos). Let me know if you think this makes sense!

**Comment by hallez** [comment]
Ahh, I had assumed that they'd already have a repo they're working w/in. I'll make those modifications and ping you again when I'm ready for you to review.

**Comment by hallez** [comment]
Paul, this should be ready for you to re-review.

**Pull request merged**
